### ISSUE TITLE
Check permissions after they are shown

### ISSUE THREAD

**Issue by HeinrichReimer** [PaoloRotolo/AppIntro#115]
If a user denies a permission request the next page is shown. The expected behavior is that the current page stays as long as the user hasn't accepted the permission request.

**Comment by Andrew-Quebe** [comment]
No it's not. Permissions are to be asked once regardless of if the user accepts or denies them. If the user doesn't want location to be used, then it's not used. 

The whole idea of Android 6.0 permissions is to give the user the choice in these matters. It would be annoying if I didn't want a permission and the app locked up because I didn't give it what it wants. 

That defeats the purpose of giving them the option to deny access to whatever is being requested!

I would consider any app that does this to be in violation of the Android guidelines. As developers, our apps should be open for users to choose what they want and don't want. If they don't want location to be used, tell them briefly why it needs to be used, but ultimately, don't annoy them because they denied access to it.

**Comment by Andrew-Quebe** [comment]
Furthermore, here's a quote from the developer docs: 

*The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request.*

http://developer.android.com/training/permissions/requesting.html

**Comment by HeinrichReimer** [comment]
At least you should have an option for both.
E.g. You implement the app intro for a file manager that would force close if it hasn't the storage permission...

**Comment by Andrew-Quebe** [comment]
@HeinrichReimer that is up to the developer of the app to implement this type of thing. The intro library is merely a way to request permissions and talk to the user about them. It does not do things based on what the user does with the request.

**Comment by HeinrichReimer** [comment]
Ok, I understand
