### ISSUE TITLE
App closes after asking for permissions

### ISSUE THREAD

**Issue by ivanmestre** [PaoloRotolo/AppIntro#128]
When using the Permissions feature , the app closes right after the permissions dialog is shown no Exception on Logcat.

**Comment by Andrew-Quebe** [comment]
Ensure you're not calling finish() in the onDonePressed method, unless you're launching the intro from your main activity. Refer to the readme or wiki for an example of how to launch the intro once from the main activity.

In theory, you want to call finish() onDonePressed because you want the activity to close. However, if you don't have an underlying activity that launched the activity, finish() will exit to the home screen.

Ensure that the intro is not your launcher activity, rather, your main activity is, and launches the intro from it.

**Comment by Andrew-Quebe** [comment]
It seems that because there isn't a crash report, the app isn't crashing, but rather finishing in an improper way. Does it say "<your app> has stopped"? Or does it just close to the home screen?

**Comment by ivanmestre** [comment]
It just closes to Home screen, I have my IntroActivity as the launcher activity and I launch my MainActivity if it is not the first start and I'm calling finish in the onDonePressed method after launching the MainActivity.

**Comment by ivanmestre** [comment]
I did it that way because when I pressed back the app showed the MainActivity which was not optimal. I'll try the other way to see if that solves the issue

**Comment by ivanmestre** [comment]
I tried it the other way and i closed to the home screen as well

**Comment by Andrew-Quebe** [comment]
@ivanmestre glad you got it working :)

One thing to note about the intro closing when pressing the back button, I'm going to open an issue for this so that I'll remember to add support for disabling the back button. That way, if you want to, you could define whether or not the back button makes the intro close.

**Comment by ivanmestre** [comment]
At the end the problem was that I had the IntroActivity with noHistory=true in the Manifest, that is what was making the app close

**Comment by eyecreate** [comment]
I've just encountered this myself: trying to suppress history causes issues. Might be useful to put in the readme so others know this could break things.

**Comment by cmengler** [comment]
Thank you @ivanmestre -- I also encountered this only on Android 6.0.1, however 7.0 seemed to work as I'd expect.

Issue was due to AppIntro activity being launched from my MainActivity with the FLAG_ACTIVITY_NO_HISTORY flag when I created the intent. Removing this, and also adding call to finish() on the AppIntro onDonePress() callback appears to have resolved it.

Just for reference for others who may stumble on this issue when requesting permissions from the app intro -- this is the final changes I made to handle the launch of the AppIntro activity from MainActivity and then launching the MainActivity after the AppIntro activity has finished.

**MainActivity.java**
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...

        // check if this is the first run, launch the introduction activity
        if (isFirstRun()) {
            startActivity(new Intent(MainActivity.this, AppIntro.class));
            finish();
            return;
        }

        ...
    }
```

**AppIntro.java**
```
    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);

        // first run of the app is complete
        setFirstRun(true);

        // finish the introduction activity
        finish();

        // launch the main activity again
        startActivity(MainActivity.createIntent(AppIntro.this));
    }
```
