### ISSUE TITLE
can't swipe anymore after adding "askForPermissions"

### ISSUE THREAD

**Issue by jeffreyliu8** [PaoloRotolo/AppIntro#133]
I tried adding the askForPermissions code in the read me sample, but after adding that line, I can't swipe on the screen anymore, everything else is working.

I added 

  askForPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.READ_CONTACTS}, 2);

**Comment by brittonjg** [comment]
If you ask for permission swipe is automatically disabled as per https://github.com/PaoloRotolo/AppIntro/issues/123

Although, having said that it would be really good if it could be restored in a future update.

**Comment by Andrew-Quebe** [comment]
The reason this isn't supported is because the way the library listens for permission requests. The listener listens for when the slide changes. If you swipe the slide a pixel, it'll trigger the permission request and cause unwanted/awkward behavior.

This is probably something we'll fix in a later update, but for now, swiping isn't that necessary since both intro classes have buttons to advance to the next slide. IMO, users are more inclined to press a button than swipe...it's what I do when going through an intro.

**Comment by xsorifc28** [comment]
The latest version does not seem to automatically disable the swiping when asking for permissions (using AppIntro2).
