### ISSUE TITLE
How to select Page?

### ISSUE THREAD

**Issue by hosseinalvandi** [PaoloRotolo/AppIntro#212]
for Example
1 - click button in other Activity go to page 2 Or 3 Or other
2 - Disable SwipeAble With Finger -   I want to swipe programatically

**Comment by avluis** [comment]
**Note: I'm not part of the library development team.**

Depending on how you have your AppIntro set up, all you need to do is pass an intent with the page number and after all the required initialization, you can check for this intent.
In order to manipulate the pager, a viewpager is provided; it's named: pager.
You can use this variable right after you have added your slides.

To navigate to a particular page (pages start at 0, as always):

    pager.setCurrentItem(page);

To get the current page (useful if you need a particular method to run only on a certain page):

    pager.getCurrentItem();

To disable manual paging, you are looking at a few possible options and if you want to disable paging entirely, then you must set them all.

To display or hide the Next or Done button:

     setProgressButtonEnabled(false);

To disable swiping left and right on current page.
_This also hides/shows the Next and Done buttons_:

    setSwipeLock(true);

On a few tablets I have, paging is enabled after init() so I usually disable that with right after I add my slides (right in the init method):

    pager.setPagingEnabled(false);

**Comment by Andrew-Quebe** [comment]
@avluis Thanks for your help :)
