### ISSUE TITLE
Bug while running once IntroActivity

### ISSUE THREAD

**Issue by Xmashine** [PaoloRotolo/AppIntro#249]
Whe starting the activity at the first time, using this wiki code:

```java

Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                if (isFirstStart) {

                    Intent i = new Intent(home.this, IntroActivity.class);
                    startActivity(i);

                    SharedPreferences.Editor e = getPrefs.edit();

                    e.putBoolean("firstStart", false);

                    e.apply();
                }
            }
        });

```
The activity was successfully showed once. but if I try to erase app data, start once the activity, kill the process and restart it, I get MainActivity instead of IntroActivity. this bug is probabilly fixable if you apply at the reported code an 
```java 
  if doneButtonIsJustPressed = false ... {
      Intent ReloadData = new Intent (MainActiity.this, IntroActivity.class);
      startActivity(ReloadData);
  } else if {

  }

```

**Comment by avluis** [comment]
While the snipped of code is from the wiki, I don't see how the issue relates to the library itself.
The run once code is simply a Shared Preference check and not something that the library handles for you.

If you are suggesting an edit to the wiki, I suggest sharing a bit more of the code you have presented, since the solution provided in the wiki is simply started code, but it does work (I am using it right now), but it is up to the developer to take care of checking Shared Preferences, and not the AppIntro library.

**Comment by avluis** [comment]
Referencing this issue as it is related #250
If this issue has not being fixed, please reopen with something substantial.
