### ISSUE TITLE
showSkipButton not available in AppIntro2

### ISSUE THREAD

**Issue by ja1984** [PaoloRotolo/AppIntro#257]
[ ] What you've tried (include code snippets, or whole files as necessary):

adding showSkipButton(false) in my onCreate

[ ] What you thought should happen:

skipButton would be hidden

[ ] What actually happened:

compilation error since method showSkipButton does not exist in AppIntro2

**Comment by avluis** [comment]
This issue is similar to #237, which has been addressed with PR #241 which will be available in the next update as it has been merged with master.

For now, add the following in your intro activity (which extends AppIntro2, AppIntro already has this method), add:

```java
private void showSkipButton(boolean showButton) {
    this.skipButtonEnabled = showButton;
    setButtonState(skipButton, showButton);
}
```

Then in `onCreate(Bundle savedInstanceState)` - in the same file (after adding your slides), call the above method:
```java
...
showSkipButton(false);
...
```
