### ISSUE TITLE
User should be able to navigate back even with isPolicyRespected false

### ISSUE THREAD

**Issue by pixis** [PaoloRotolo/AppIntro#266]
[ ] What you've tried (include code snippets, or whole files as necessary):

Implemented ISlidePolicy in a fragment and in isPolicyRespected return false

[ ] What you thought should happen:

User should not be able to go forward but he can go backwards

[ ] What actually happened:

User cant move forward or backwards

**Comment by seang96** [comment]
Experiencing the same issue and need to be able to navigate backwards.

**Comment by avluis** [comment]
Have you tried doing the following:
* Check the position of the fragment being returned via `onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment)`
* If the position of the fragment being requested is before the current fragment, allow changing fragment

In order to accomplish the above, override `onCanRequestNextPage()` with said logic.

**Comment by avluis** [comment]
Closing due to non-interest.
Please reopen if this issue persists and you wish to add to the discussion.

**Comment by idish** [comment]
I don't really understand why the said above isn't the default behavior, and users should do some custom overrides of the base class. Can this be fixed in the library itself?
