### ISSUE TITLE
Demo-App: Many deprecated methods are used

### ISSUE THREAD

**Issue by Rainer-Lang** [PaoloRotolo/AppIntro#268]
Example:
- DepthAnimation

**Comment by avluis** [comment]
Demo App is being updated as you submit this issue via a PR -- how about that?
I'm not sure how this qualifies as an issue either, yes, the demo app needs to be updated; that just shows that the last PR that made changes did not update the demo app.

I'm not seeing much discussion out of this issue since it is already being addressed, but thanks for letting us know what we already know :+1:

**Comment by Andrew-Quebe** [comment]
@Rainer-Lang you didn't really provide any info for the issue...therefore it doesn't qualify one. PR #267 is going to bring a lot of updates, and the demo app will be updated accordingly.
