### ISSUE TITLE
Setting Image Size 

### ISSUE THREAD

**Issue by beraybentesen** [PaoloRotolo/AppIntro#277]
Is is possible to change or set width & height of images ?

**Comment by avluis** [comment]
https://guides.codepath.com/android/Working-with-the-ImageView

**Comment by beraybentesen** [comment]
@avluis Thanks for introduction to ImageView. I asked for ImageView that shipped with wrap_content for both width & height in your library. I would like to use your library if it is possible to access that imageView, I will create my own library otherwise.

**Comment by avluis** [comment]
I don't think I get what the issue is.
You can definitely set the size of ImageView, which is why I linked to that tutorial since there wasn't a lot to go on with: 
> Is is possible to change or set width & height of images ?

If you want to modify the way the ImageView is defined in the default layout(s), then create your own layout(s) based on those defaults.

**Comment by abumoallim** [comment]
The issue is that the images that are kept through R.drawable
  addSlide(AppIntroFragment.newInstance("","",R.drawable.a1, Color.TRANSPARENT)); does not take full width and height . is there any way to adjust the width and height of drawable image in your code for betterment or can u suggest any other way ?

**Comment by casablancaplusplus** [comment]
you can easily find the responsible layout xml file and copy its code to your custom fragment then edit the size of the displayed image.
