### ISSUE TITLE
Asking for 2 permissions on the same slide

### ISSUE THREAD

**Issue by zoff99** [PaoloRotolo/AppIntro#306]
[ ] What you thought should happen:
asking for 2 permission on 1 slide. only go to next slide if both permissions are granted

[ ] What actually happened:
asking for 2 permission on 1 slide. if i only allow 1 or deny both, it adances to next slide
also when sliding to next slide (not perssing next button) permissions are never asked!

**Comment by avluis** [comment]
Where is your code?
Are you overriding this:
```java
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        // my preferred behaviors
    }

**Comment by zoff99** [comment]
onRequestPermissionsResult never gets called. i use the exact code from your example:

![unbenannt](https://cloud.githubusercontent.com/assets/6833516/18809997/710e9414-828b-11e6-83ee-3f01b7d643e8.PNG)

it does not say anything about onRequestPermissionsResult. it says actually "single line"

**Comment by zoff99** [comment]
also its not clear what "second slide" means? does it start at 0 or 1 ?

**Comment by Andrew-Quebe** [comment]
@zoff99 this library doesn't do anything based off what permissions the user selects on purpose. The library is intended to only ask for permission and not do anything based on it. Since it's an intro, the permissions are meant to be straight forward, and not restrict the user from entering the app if they don't allow "x" permission. This is handled later in your UI.

Second slide means second slide ;) we add one in our indexes to make it easier for you.
