### ISSUE TITLE
Backward navigation with Slide Policy

### ISSUE THREAD

**Issue by janakagamini** [PaoloRotolo/AppIntro#332]
**AppIntro Version**: 4.0.0

**Device/Android Version**: API versions 16-24

**Issue details / Repro steps / Use case background**:
This is not really an issue, but I'm trying to figure out if backward navigation is possible even if slide is failing to respect Slide Policy. I.e. only forward navigation should be prevented when Slide Policy is not obeyed.

**Your Code**:
This is just a use case requirement. The user is free to go back to a previous slide as and when he/she pleases, but to move forward he/she is required to meet certain conditions on the slide (e.g. accept terms & conditions).

**Comment by avluis** [comment]
Thank you for following the template -- please do us a favor and check for prior issues before opening new ones on your next issue, here is the prior issue for relevance #266

---
As for your question, I would need to look a bit further into the library since I believe there is a method you can override to return true when the slide is changing to allow said slide change (you would need to check if the slide number is less than the current slide, etc).

**Comment by janakagamini** [comment]
@avluis Noted and apologies, I only did a cursory search and did not find the previous issue.

**Comment by avluis** [comment]
No big deal -- While the slide policy is a good option to use, if you require backward navigation (and if slide policy doesn't provide a way to override), I suggest taking a look at how that is implemented and follow along with your own on your Intro Activity.
Would love to have all possible options integrated into the library but sometimes that is not possible.
Let me know if you find what you are looking for before I dig into it later (it's late here).

**Comment by janakagamini** [comment]
Its not critical, just checking whether there was already a method in the library to do this, before getting around to implementing it myself.

Thanks for the reply!
