### ISSUE TITLE
How to handle permissions,if reject,do not go next slide?

### ISSUE THREAD

**Issue by erginduran** [PaoloRotolo/AppIntro#342]
**AppIntro Version**:4.1.0

**Device/Android Version**:Galaxy S6 6.0.1

**Issue details / Repro steps / Use case background**: Question

How to handle permissions with askForPermissions() method? if user reject a permission,do NOT go next slide till user agree that permission?
i need absolute solutions about this permission things after this marshmellow rules.

**Comment by Andrew-Quebe** [comment]
This has already been addressed in #115.

_The intro library is merely a way to request permissions and talk to the user about them. It does not do things based on what the user does with the request._

**Comment by Andrew-Quebe** [comment]
A side note: are you really wanting to lock someone out of your app if they don't accept a single permission? It seems like a turn off for me. Later in your app, you can explain why a permission is necessary, but an intro is just getting the user acquainted with your app...it's the first thing they see, therefore it shouldn't kick them out if they don't want a permission. Inevitably, some people will deny permissions, and the UI should not lock based on their decision.

**Comment by erginduran** [comment]
idk i thought there is a way or method to avoid user pass that slide like policy slides.if user does not check box,user can not skip that slide, does he? i need smiliar thing :D

**Comment by avluis** [comment]
@erginduran If you really want to lock your users endlessly then simply check for that particular permission in `onSlideChanged` after the appropriate slide has been triggered and simply move the user back to the slide where explain why that permission is needed (you do have that, right).

Note that many users will simply not bother or complain if they see no reason for your app to have said permission -- while some apps it is easier to explain (needing location on a GPS app) while others not so much (needing phone access in order to uniquely identify device).

**Comment by erginduran** [comment]
i checked that onslidechanged method already deprecated and can't find that onslidechanged(Fragment,Fragment) but i just noticed a trick if i implement ISlidePolcy interface to fragment then i can handle this condition in isPolicyRespected(). I hope i can do :p thank you for this powerfull repo !

**Comment by J4S0Nc** [comment]
Keep in mind just because they allowed the permission today, they can turn if off at any time in the application manager. You need to ensure your application can still function without it.
