### ISSUE TITLE
askForPermissions always shows permission popup

### ISSUE THREAD

**Issue by BackEndCode** [paolorotolo/AppIntro#348]
I have added appintro library in my app and asked for some permission from user but the problem is it always shows permission popup no metter user granter permission or not.
I should check if the asked permissions are granted already or not.
I am showing all the tutorial in the intro screens so user can visit it whenever he wants every time user visits i gets permission popup.

**Comment by Andrew-Quebe** [comment]
This should be closed since it ignored the template. BUT...let me solve your issue real quick: AppIntro does not query whether the permissions have been asked for before because it's an intro...of course they haven't been asked for before.

And if you've given your users a way to open the intro again, this presents them with another opportunity to choose which permissions they want and don't want, without having to reset your app.
