### ISSUE TITLE
A small Readme Update

### ISSUE THREAD

**Issue by ziadkiwan** [paolorotolo/AppIntro#387]
Hello, first thanks for the great repo and for the hard work you put in to make it easier on us 👍 ,
can you update the readme to put what versions this appintro works on like 5+ or 4+ or ? i have an application that works on android 4+ does this intro works on it ? thank you!

**Comment by avluis** [comment]
Let me give you a quick tip that will not only help you figure this out for this library but for many others so that you'll know what is compatible or not.
Don't take this as an insult or anything, just want to educate other developers with what I know.

When taking a look at an application, or a library in this case, look for the `build.gradle` file included in the `app` (in case of an application) or in the `library` directory (in case of a library) -- in AppIntro, this would be [here](https://github.com/paolorotolo/AppIntro/blob/master/library/build.gradle).

Checking out the contents of this file, we see the following:
```gradle
apply plugin: 'com.android.library'
apply plugin: 'maven'
apply plugin: 'signing'
apply from: 'maven-push.gradle'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"

    defaultConfig {
        minSdkVersion 11
        targetSdkVersion 25
        versionCode 13
        versionName "4.1.0"

        consumerProguardFiles 'consumer-proguard-rules.pro'
        vectorDrawables.useSupportLibrary = true
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:support-annotations:25.0.1'
}
```
What we care about, in the android block, are the following:
`compileSdkVersion`, `buildToolsVersion`, `minSdkVersion` and `targetSdkVersion`.
- `compileSdkVersion`: You'll need to have this SDK version installed in order to include the library.
- `buildToolsVersion`: These are the tools -- you'll want this as well.
- `minSdkVersion`: This is the lowest SDK version in which the library has been tested to compile on without loosing too many features -- you can cross reference that [here](https://source.android.com/source/build-numbers.html) to figure out the Android version.
- `targetSdkVersion`: While the library will work with the minimum SDK level above, you really want to be on the latest SDK level if possible -- this is the SDK level that the library itself is targeting; you want to have this installed.

What do you think? The above should answer your question fairly well.

**Comment by ziadkiwan** [comment]
Hello Avluis thank you for the helpful answer, and for the great educational information it contains 👍yeah i got the answer ! thank you again!
