### ISSUE TITLE
AndroidX only?

### ISSUE THREAD

**Issue by chrisonline** [paolorotolo/AppIntro#610]
Can I use this library only if I update my app to AndroidX?
I use the V28 of the support library at the moment. Not migrated to AndroidX yet.

After try using the library I get this problem:
`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:53:5-458:19 to override.
`

Also my custom Fragment is of course from android.suppor.v4.app instead of androidx.
So I get also a problem if I want to add my Fragment to addSlide(new FragmentSlide().fragment()) because this wants an androidx Fragment.

**Comment by cortinico** [comment]
Hey @chrisonline

Yup that's the intended behavior. The v5.+ version of AppIntro supports only AndroidX. I highly encourage you migrate your project to AndroidX as this is the direction Google is taking with Android projects. You will find more and more libraries that update to AndroidX in the future.

If you still want to use AppIntro you can either:

- Use version `v4.2.3`, the latest version without AndroidX support (recommended)
- Use Jetifier in _reverse_ mode (see here https://developer.android.com/studio/command-line/jetifier#reverse_mode) on the AppIntro .aar. I honestly never tried this so I don't think if is worth the effort to let it work rather than converting your project to AndroidX.

**Comment by cortinico** [comment]
Hey @chrisonline 

> Yes of course I have to migrate to AndroidX, but if I do all my other libraries I use have to be on AndroidX too.

Not really. You can use Jetifier (in the _regular_ mode) to achieve the opposite result. That's exactly what this was designed for :D Just add:

```
android.useAndroidX=true
android.enableJetifier=true
```

To your `gradle.properties` file and all the bytecode from non-AndroidX library will be converted to be AndroidX compatible. More on this on: https://developer.android.com/jetpack/androidx/migrate

**Comment by chrisonline** [comment]
Thank you very much for the info. 
Will try and use the "jetifier" thing.
