### ISSUE TITLE
Support transparent bottom navigation bar on API 19+

### ISSUE THREAD

**Issue by ZakTaccardi** [PaoloRotolo/AppIntro#89]
Having a transluscent bottom navigation bar makes the intro screen a lot prettier. Google Photos does this now

**Comment by Andrew-Quebe** [comment]
Coming in the next release along with #69.

**Comment by filippofavaro** [comment]
Andrew is there a planned date for the next version release?

**Comment by Andrew-Quebe** [comment]
So, @PaoloRotolo and I did some discussing of this issue and we've come to the decision that we think it's best if the user of the library handles the translucent nav bar. The reason for this is because you're extending the app intro activity and should be able to apply your own styles to it. This would include the nav bar translucency. For this reason, I'm closing this issue. Some good news though: users now have the option to show the statusbar which is transparent as it should be. 

Changes will be released soon.
