### ISSUE TITLE
Support Min Api 11

### ISSUE THREAD

**Issue by ligol** [PaoloRotolo/AppIntro#91]
As it seem to be ou switch from API 8 to 14, but all of the method concerned by this change and used now are available since API 11. Is it possible to set the min API to 11 instead of 14?

Thanks.

**Comment by janakagamini** [comment]
Very nice library, however I also need need min API 11.

**Comment by ligol** [comment]
Can you use it, at this time by adding this line to your manifest.
<uses-sdk tools:overrideLibrary="com.github.paolorotolo.appintro"/>

But be careful, and spend a good time testing your intro on old devices.

**Comment by TroniPM** [comment]
@ligol what line? I'm needing it.

**Comment by HeinrichReimer** [comment]
SDKs under 14 are considered outdated by Android Studio and Google.
SDK14 has over 95% of active android devices and app developers should consider updating their min SDK to 14 except for when thei really really need to support lower versions.

This library doesn't claim to support 100% of android devices so I suppose 95% are enough and therefore min sdk should stay 14.

**Comment by markusressel** [comment]
Im with @HeinrichReimer on this, 14 is old enough. I'm currently deciding to up my minSDK from 9 to 14 because I ran into a common "too many/complicated methods/libraries" problem on older Versions of Android which apparently can't be fixed without simplifying the app which is anti-progressive imo. And my app isn't even that big.
