### ISSUE TITLE
Problem with startActivityForResult: Interactive AppIntro

### ISSUE THREAD

**Issue by Nem2s** [PaoloRotolo/AppIntro#96]
My question is: i tried to implement AppIntro2 for a custom Intro in my app that wil be show ONLY at first boot of the App. I tried to do that with an "startActivityForResult" but its result is: **"trying to requery an already closed cursor"**.
Unfortunatly my knowledge about fragments is so poor, so i don't know if it's releated to it.

P.S
Is there a fast way to implement some "toggles" inside the activity on page 1, page 2 etc..?
I need to load data from a db firstly, then select some toggles according to data gathered and finally shows some toggle for the user. It's possible to do that?

**Comment by brunano21** [comment]
I think we have the same 'problem'..[#92](https://github.com/PaoloRotolo/AppIntro/issues/92)
I'm still waiting for answers..fingers crossed :)

**Comment by Andrew-Quebe** [comment]
@Nem2s if you're attempting to launch the intro for the first time on app startup, a simple boolean sharedPreference will do. Simply define a isFirstStart variable in shared preferences and check if it's true. If it is, launch the intro, otherwise don't. This code should be run in a thread on the main activity AFTER everything else has been built (nav drawer if you're using one, toolbar, etc.). In other words, at the end of your onCreate method.

@brunano21 I'm still going to research #92 but have been busy with other projects! Will keep you updated as soon as I know more.

**Comment by Nem2s** [comment]
@Andrew-Quebe thank you, resolved. Could you answer to my second question? Can't show the fragment correctly :(

**Comment by Andrew-Quebe** [comment]
@Nem2s with regard to toggles, look into loading custom fragment views. The library supports this.
